spring:
  application:
    name: applicant-services
server:
  port: 8081
  servlet:
    context-path: /applicants

logging:
  level:
    root: INFO
    com.czetsuyatech: DEBUG

resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
  retry:
    instances:
      default:
        maxRetryAttempts: 5
        waitDuration: 1
        enableExponentialBackoff: true
