spring:
  application:
    name: job-services
server:
  port: 8080
  servlet:
    context-path: /jobs
logging:
  level:
    root: INFO
    com.czetsuyatech: DEBUG
app:
  ct:
    client:
      applicant:
        url: ${APPLICATION_SERVICE_URL:http://localhost:8081}
